# -*- coding: utf-8 -*-
"""DataScienceEcosystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zcSyCGEJ8iiupLe4kBj8-H-mq_mPJkZE

#Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.\
Some of the popular languages that Data Scientists use are:
1. Python
2. R
3. SQL

Some of the commonly used libraries used by Data Scientists include:
- Pandas
- NumPy
- sklearn

| Data Science Tools |
| ----------- |
| python |
| spark |
| Apche Hadoop|
|TensorFlow|

Below are a few examples of evaluating arithmetic expressions in Python.
"""

#This a simple arithmetic expression to mutiply then add integers
(3*4)+5

#This will convert 200 minutes to hours by diving by 60
200/60

"""List popular languages for Data Science:
- python
- R
- SQL

## Maram Alzahrani
"""